// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:32e85722-f280-43f8-a5f6-fc1bb21c9a1a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xO1HJ3bCk",
    "aws_user_pools_web_client_id": "fknhclktrcj5l7eeagq9cg34v",
    "aws_appsync_graphqlEndpoint": "https://xtsopdwgijfxhdachshesjesuy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
