// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eed975b5-f19d-448a-afb4-25e2310838fa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xtHzOk263",
    "aws_user_pools_web_client_id": "5u2tmmcd5s7opq2afrv0glf07e",
    "aws_appsync_graphqlEndpoint": "https://qkky6re27bcfvlzwoo6c6pa4yi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
